import { Issuer, ReplicationMethod, UseOfProfit, Domicile } from '@/lib/types';

export const STORAGE_KEY = 'etf_portfolio_data';

export const DEFAULT_ETFS = [
  {
    name: 'Vanguard North America',
    issuer: 'Vanguard' as Issuer,
    isin: 'IE00BK5BQW10',
    ter: 0.08,
    path: '/static/example_csv/vanguard-north-america.csv',
    weight: 25,
    replicationMethod: 'Physical' as ReplicationMethod,
    fundSize: 2613,
    fundAge: 7,
    useOfProfit: 'Accumulating' as UseOfProfit,
    domicile: 'Ireland' as Domicile,
  },
  {
    name: 'Amundi Stoxx Europe 600',
    issuer: 'Amundi' as Issuer,
    isin: 'LU0908500753',
    ter: 0.07,
    path: '/static/example_csv/amundi-stoxx-europe-600.csv',
    weight: 30,
    replicationMethod: 'Physical' as ReplicationMethod,
    fundSize: 19220,
    fundAge: 13,
    useOfProfit: 'Accumulating' as UseOfProfit,
    domicile: 'Luxembourg' as Domicile,
  },
  {
    name: 'Amundi Prime Japan',
    issuer: 'Amundi' as Issuer,
    isin: 'LU2089238385',
    ter: 0.05,
    path: '/static/example_csv/amundi-prime-japan.csv',
    weight: 5,
    replicationMethod: 'Physical' as ReplicationMethod,
    fundSize: 570,
    fundAge: 6,
    useOfProfit: 'Accumulating' as UseOfProfit,
    domicile: 'Luxembourg' as Domicile,
  },
  {
    name: 'iShares MSCI EM',
    issuer: 'iShares' as Issuer,
    isin: 'IE00BKM4GZ66',
    ter: 0.18,
    path: '/static/example_csv/ishares-msci-em.csv',
    weight: 20,
    replicationMethod: 'Physical' as ReplicationMethod,
    fundSize: 36407,
    fundAge: 12,
    useOfProfit: 'Accumulating' as UseOfProfit,
    domicile: 'Ireland' as Domicile,
  },
  {
    name: 'iShares MSCI Pacific ex-Japan',
    issuer: 'iShares' as Issuer,
    isin: 'IE00B52MJY50',
    ter: 0.2,
    path: '/static/example_csv/ishares-msci-pacific.csv',
    weight: 20,
    replicationMethod: 'Physical' as ReplicationMethod,
    fundSize: 3131,
    fundAge: 16,
    useOfProfit: 'Accumulating' as UseOfProfit,
    domicile: 'Ireland' as Domicile,
  },
];
